id: I513B7828
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T09:47:54.112465'
last_modified: '2022-06-19T09:47:54.112476'
parser: null
source_metadata:
  title: Autobiography of sNgags chang bSod nams chos phel (1527–1603) of Bru; Lamdre
    Lobshe, vol. nga, title no. 3
  author: སྔགས་འཆང་བསོད་ནམས་ཆོས་འཕེལ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-03);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/569
  bases:
    35c1:
      title: Autobiography of sNgags chang bSod nams chos phel (1527–1603) of Bru;
        Lamdre Lobshe, vol. nga, title no. 3
      order: 1
      base_file: 35c1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
